### ISSUE TITLE
Training setting

### ISSUE THREAD

**Issue by ashkan-abbasi66** [XiaLiPKU/RESCAN#1]
Hello
Can you please provide a better usage instruction for the algorithm? I did these steps:
1- I created three folders:
`../logdir/`
`../models/`
`../showdir/`
2- I downloaded the RAIN800 dataset which has three folders inside a folder with name `rain`:
`rain/test_nature: 92 real rainy photographs.`
`rain/test_syn: 100 images.`
`rain/training: 700 images. `
3- I changed the name of the last folder.
training ---> train
Then, I set `data_dir = 'path/to/dataset/folder'` in settings.py file to `rain`. for example, the algorithm addresses the train folder as `rain/train`.
4- I intentionally disabled all the codes which are used for validation to avoid extra errors. (please specify the validation dataset.)
5- I triggered the training command as `python main.py -a train`

But stilll I encountered the following error:
```
INFO - train--loss0:0.004158 loss1:0.00411 loss2:0.004155 loss3:0.004152 ssim0:0.7887 ssim1:0.8015 ssim2:0.7991 ssim3:0.7981 lr:0.005 step:1092
Traceback (most recent call last):
  File "main.py", line 227, in <module>
    run_train_val(args.model)
  File "main.py", line 170, in run_train_val
    batch_t = next(dt_train)
  File "C:\Users\ashkan\Anaconda3\envs\pytorch\lib\site-packages\torch\utils\data\dataloader.py", line 276, in __next__
    raise StopIteration
StopIteration
```

Regards,
Ashkan.

**Comment by AllenIrving** [comment]
Hi there. I've been reading the paper and tried to understand the codes as well. Here is what I think.
First, the Rain800 contains the training dataset and the validation dataset. The folder named "test_syn" containing 100 images should be the validation dataset. So you could rename it to "val". 
Then, you may need to download the Rain100H dataset(http://www.icst.pku.edu.cn/struct/Projects/joint_rain_removal.html). This is actually the testing dataset. After that, you may want to create a new folder named "test" under your dataset folder. Then take 100 rainy images from the Rain100H and move them to the "test" folder. 
I think that is all in terms of preparing the dataset. Hope it can help.

**Comment by SherlockSunset** [comment]
Hello,
when I was runing the codes as "test", that is: python main.py --action test
it raised one error like this: 
2018-09-05 17:28:12,461 - INFO - set log dir as ../logdir
2018-09-05 17:28:12,461 - INFO - set model dir as ../models
Traceback (most recent call last):
  File "main.py", line 229, in <module>
    run_test(args.model)
  File "main.py", line 205, in run_test
    for i, batch in enumerate(dt):
  File "C:\Users\pengx\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 314, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices]) ###
  File "C:\Users\pengx\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 184, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "C:\Users\pengx\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 184, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in batch[0]}
  File "C:\Users\pengx\AppData\Local\Programs\Python\Python36\lib\site-packages\torch\utils\data\dataloader.py", line 173, in default_collate
    return torch.stack([torch.from_numpy(b) for b in batch], 0)
RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 481 and 321 in dimension 2 at c:\new-builder_3\win-wheel\pytorch\aten\src\th\generic/THTensorMath.cpp:3616

Does anyone know how to fix this problem??

**Comment by KCHENPENGFEI** [comment]
> Hi there. I've been reading the paper and tried to understand the codes as well. Here is what I think.
> First, the Rain800 contains the training dataset and the validation dataset. The folder named "test_syn" containing 100 images should be the validation dataset. So you could rename it to "val".
> Then, you may need to download the Rain100H dataset(http://www.icst.pku.edu.cn/struct/Projects/joint_rain_removal.html). This is actually the testing dataset. After that, you may want to create a new folder named "test" under your dataset folder "rain". Then take 100 rainy images from the Rain100H and move them to the "test" folder.
> I think that is all in terms of preparing the dataset. Hope it can help.

Hi, what about the "train" folder? which type photo should i put in this folder?

**Comment by adityac8** [comment]
Hi,
Could you tell me where can I download the original Rain800 dataset.
Thanks
