### ISSUE TITLE
Problems encountered during retraining

### ISSUE THREAD

**Issue by yangling111** [XiaLiPKU/RESCAN#11]
前辈，您好！近段在学习您上传的代码，并作了以下实验：
    实验1.训练集用R800里的700张图像，验证集用R800里的100张图像，测试集用R100H。 结果为： ssim-0.75    psnr-24.01
    实验2.训练集用rain_data_train_Heavy-R100H里的1800张图像，验证集和测试集都用rain_heavy_test-R100H里的200张图像。 结果为： ssim-0.42    psnr-14.19  目前尝试了多次改动，效果都不太理想。。。
     所有的数据格式都是左图为标签图，右图为雨图的拼接图像。在训练和测试过程中没有对代码做其它改动（我将您代码里的参数设置与您的论文进行了对照，都是一致的）。 但是，所得到的实验结果却和您论文里相差很大。不知是哪些步骤出了问题？请指点，谢谢！

**Comment by XiaLiPKU** [comment]
我想看下你写的settings

**Comment by yangling111** [comment]
> 我想看下你写的settings

非常感谢您的回复。两个实验的settings除了路径不一致，其它设置都是：

import os
import logging:
channel = 24
stage_num = 4
depth = 7 # >=3
use_se = True 
uint = 'GRU' # ['Conv', 'RNN', 'GRU', 'LSTM']
frame = 'Full' # ['Add', 'Full']
aug_data = False # Set as False for fair comparison
batch_size = 64
patch_size = 64
lr = 5e-3

data_dir = '/home/abc/xinyiyuan/rain100HTrain'
log_dir = '../logdir'
show_dir = '../showdir'
model_dir = '../models'
log_level = 'info'
model_path = os.path.join(model_dir, 'latest')
save_steps = 400
num_workers = 8
num_GPU = 1
device_id = 0

logger = logging.getLogger('train')
logger.setLevel(logging.INFO)

ch = logging.StreamHandler()
ch.setLevel(logging.INFO)

formatter = logging.Formatter('%(asctime)s - %(levelname)s - %(message)s')
ch.setFormatter(formatter)
logger.addHandler(ch)

**Comment by XiaLiPKU** [comment]
@yangling111 Which format do you use to save image pairs? PNG or JPG? That's of significance.

**Comment by yangling111** [comment]
前辈，您好！我保存时用的png格式。 1075826261 邮箱：1075826261@qq.com 签名由 网易邮箱大师 定制 On 04/01/2019 14:03, XiaLiPKU wrote: @yangling111 Which format do you use to save image pairs? PNG or JPG? That's of significance. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by XiaLiPKU** [comment]
> 前辈，您好！我保存时用的png格式。 1075826261 邮箱：1075826261@qq.com 签名由 网易邮箱大师 定制 On 04/01/2019 14:03, XiaLiPKU wrote: @yangling111 Which format do you use to save image pairs? PNG or JPG? That's of significance. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Right now, I don't what's wrong with you execution. You may send me a mail, and I'd like to share my personal though that.

**Comment by githubPsearth** [comment]
> > 前辈，您好！我保存时用的png格式。 1075826261 邮箱：[1075826261@qq.com](mailto:1075826261@qq.com) 签名由 网易邮箱大师 定制 On 04/01/2019 14:03, XiaLiPKU wrote: @yangling111 Which format do you use to save image pairs? PNG or JPG? That's of significance. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.
> 
> Right now, I don't what's wrong with you execution. You may send me a mail, and I'd like to share my personal though that.

您好，我也遇到了同样的问题，在r100h上效果不理想，且参数设置论文中相同。可以向我分享一下您的经验吗？邮箱：466123174@qq.com
