### ISSUE TITLE
problem encountered during running eval.py

### ISSUE THREAD

**Issue by githubPsearth** [XiaLiPKU/RESCAN#12]
when the test datasets were solved at 80th batch, I encountered the problem: out of memory, and I found when the eval.py running , memory usage is getting bigger. I don't know why that happened.

**Comment by XiaLiPKU** [comment]
Hi, eval.py runs inference upon the full image. So if your GPU is limited, you may have two choices:
1. Run it on CPU.
2. Hack eval.py with sliding-window(must be overlapped) way

**Comment by jilner** [comment]
hello could you tell me how to load the pre_trained model ?

**Comment by XiaLiPKU** [comment]
> 
> 
> hello could you tell me how to load the pre_trained model ?

By now, I haven't publish the pretrained model.
