### ISSUE TITLE
The updates of "h" in ConvGRU and ConvLSTM in model.py

### ISSUE THREAD

**Issue by AllenIrving** [XiaLiPKU/RESCAN#2]
Hi. I read the codes in _model.py_. When it came to forward method in class ConvGRU, I noticed that the update of h you wrote, quoted
`h = (1 - z) * h + z * n`
Shouldn't it be like `h = (1 - z) * n + z * h`? I've been focused on CNN for a while and just begin to learn RNN and GRU. I wonder if there is any difference between the update of h in GRU and ConvGRU. I really appreciate it if you or anyone can help me out on this line of code.

**Comment by AllenIrving** [comment]
In ConvLSTM.forward(), you used `h = o * c` to update hidden state h. Shouldn't it be `h = o * tanh(c)` according to the formulas of LSMT? Looking forward to your reply, thanks.

**Comment by XiaLiPKU** [comment]
> I've read some blogs about GRU, and I found that some blogs referred to the update of h as `h=(1-z)*n+z*h`, and others wrote as `h=(1-z)*h+z*n`. Is any difference between these two equations? I really appreciate it if you could reply. Thanks.

They are equal in mathematics.

**Comment by XiaLiPKU** [comment]
> In ConvRNN.forward(), the code goes:
> 
> ```
> if h is None:
>         h = F.tanh(self.conv_x(x))
> else:
>         z = F.tanh(self.conv_x(x) + self.conv_h(h))
> 
> h = self.relu(self.se(h))
> return h, h
> ```
> What does "z" represent? Looks like "z" is not used or returned, and "h" is only used in _self.relu()_. Could you please tell me what exactly "z" does here? Thanks!

z is used in ConvGRU, not in ConvRNN

**Comment by XiaLiPKU** [comment]
> In ConvLSTM.forward(), you used `h = o * c` to update hidden state h. Shouldn't it be `h = o * tanh(c)` according to the formulas of LSMT? Looking forward to your reply, thanks.

Thanks a lot. This is really a bug in this code.

**Comment by XiaLiPKU** [comment]
> In ConvLSTM.forward(), you used `h = o * c` to update hidden state h. Shouldn't it be `h = o * tanh(c)` according to the formulas of LSMT? Looking forward to your reply, thanks.

This is really a bug in code, thanks for your attention!
