### ISSUE TITLE
使用show.py测试时放入网络的是没有雨的图的问题？

### ISSUE THREAD

**Issue by butyuhao** [XiaLiPKU/RESCAN#6]
dataset.py中O = np.transpose(img_pair[:, w:], (2, 0, 1))一句取的是合成图中右边的没有雨的那张图，是不是应该写成O = np.transpose(img_pair[:, :w], (2, 0, 1))?

**Comment by XiaLiPKU** [comment]
This depends on how you prepare image pairs.

**Comment by butyuhao** [comment]
OK, thanks!

**Comment by yangling111** [comment]
您好！能否向您请教一些有关此代码的问题，我的邮箱1075826261@qq.com，，期待您的邮件。。。

**Comment by jilner** [comment]
你好，请问预训练模型是models/our_net_G.t7吗？如何加载呢？谢谢

**Comment by sherlybe** [comment]
> 

老哥，这篇论文你研究的咋样，我测试了一下，出来的数值效果可以，但是雨纹是一点也没去除，我怀疑也是读取图像左右有问题。
