### ISSUE TITLE
RuntimeError: The size of tensor a (241) must match the size of tensor b (240) at non-singleton dimension 3

### ISSUE THREAD

**Issue by emu1200tra** [XiaLiPKU/RESCAN#7]
RuntimeError: The size of tensor a (241) must match the size of tensor b (240) at non-singleton dimension 3

I get this error when I try to run eval.py. 
Does anyone get this error as well and know how to fix it? 
Thanks!

**Comment by githubPsearth** [comment]
I got the same error

**Comment by XiaLiPKU** [comment]
This may caused by odd size of the input image pair

**Comment by anruoxi123** [comment]
我也遇到了这个问题，请问是怎么解决的呢

**Comment by XiaLiPKU** [comment]
The default input setting of test.py, is that you prepare a pair of O, B into a single image. So you must make sure, the width of the image must be even!!
