### ISSUE TITLE
test数据集效果甚微

### ISSUE THREAD

**Issue by githubPsearth** [XiaLiPKU/RESCAN#9]
我按照之前被关闭的issue里讲的dataset设置方式，将Rain800设置为train集和val集，Rain100H设置为test集，运行train.py后，运行show.py，但是showdir里的图片显示几乎没有derain效果。
请问我该怎么做，才能复现论文里的结果呢？

**Comment by songpeilun123** [comment]
> 我按照之前被关闭的issue里讲的dataset设置方式，将Rain800设置为train集和val集，Rain100H设置为test集，运行train.py后，运行show.py，但是showdir里的图片显示几乎没有derain效果。
> 请问我该怎么做，才能复现论文里的结果呢？

你好，我得到的结果和你的一样，show.py运行的结果去雨效果很差，请问你找到解决方法了么？

**Comment by githubPsearth** [comment]
> > 我按照之前被关闭的issue里讲的dataset设置方式，将Rain800设置为train集和val集，Rain100H设置为test集，运行train.py后，运行show.py，但是showdir里的图片显示几乎没有derain效果。
> > 请问我该怎么做，才能复现论文里的结果呢？
> 
> 你好，我得到的结果和你的一样，show.py运行的结果去雨效果很差，请问你找到解决方法了么？

还没有，最近没有空，想之后仔细看看代码

**Comment by XiaLiPKU** [comment]
有可能test里O,B放反了，可以仔细check一下。之前有几个哥们儿出这问题

**Comment by yangling111** [comment]
你好！请问你复原出作者的效果了吗？能否加个扣扣沟通下，1075826261。
